version: "3.8"

#Extension fields
x-app: 
  &x-app
  image: "node:16"
  working_dir: $PWD
  networks:
    - contact
  environment:
    VIRTUAL_HOST: "api.contact.localtest.me"
    VIRTUAL_PORT: "8080"
  volumes:
    - ./:$PWD

services:
  web:
    <<: *x-app
    depends_on:
      - db
      - nginx-proxy
    env_file: .env
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
      - 8080:8080
    expose:
      - 8080
      - 4001
      - 4002
    command: "npm run start"
    
  compile:
    <<: *x-app
    command: "npm run compile"

  db:
    image: postgres:10.6-alpine
    restart: always
    environment:
      POSTGRES_DB: contact
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - contact
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - db
      - nginx-proxy
    environment:
      VIRTUAL_HOST: "db.contact.localtest.me"
      VIRTUAL_PORT: "8080"
    ports:
      - 8002:8080
    expose:
      - 8080
    networks:
      - contact
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /etc/nginx/certs
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - contact
volumes:
  postgres:
  
networks:
  contact: