version: "3.8"

#Extension fields
x-app: 
  &x-app
  image: "node:16"
  working_dir: $PWD
  environment:
    - NODE_ENV=development
  volumes:
    - ./:$PWD

services:
  web:
    <<: *x-app
    env_file: .env
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
      - 8080:8080
    expose:
      - 8080
      - 4001
      - 4002
    command: "npm run start"
    networks:
      - contato
  compile:
    <<: *x-app
    command: "npm run compile"

networks:
  contato: