name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  DATABASE_URL: "postgresql://postgres:postgres@db:5432/contact?schema=public"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      
      with:
        node-version: '16'
    - name: Install dependencies
      run: make install
      
    - name: Run check lint
      run: make lint
      
    - name: Run test
      run: make test
